# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Char',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charName', models.CharField(max_length=250)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fluesse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstX', models.IntegerField()),
                ('firstY', models.IntegerField()),
                ('secondX', models.IntegerField()),
                ('secondY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Karte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reichszugehoerigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseLink.Reich')),
            ],
        ),
        migrations.CreateModel(
            name='Ruestgueter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('type', models.IntegerField()),
                ('directiom', models.CharField(max_length=2)),
                ('firstX', models.IntegerField()),
                ('firstY', models.IntegerField()),
                ('secondX', models.IntegerField()),
                ('secondY', models.IntegerField()),
                ('reich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseLink.Reich')),
            ],
        ),
        migrations.CreateModel(
            name='Truppen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armyId', models.IntegerField()),
                ('count', models.IntegerField()),
                ('leaders', models.IntegerField()),
                ('mounts', models.IntegerField()),
                ('lkp', models.IntegerField()),
                ('skp', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('reich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseLink.Reich')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250)),
                ('secondName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Zugreihenfolge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zugNummer', models.IntegerField()),
                ('reihenfolge', models.IntegerField()),
                ('subZug', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reichszugehoerigkeit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseLink.User'),
        ),
        migrations.AddField(
            model_name='karte',
            name='reich',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseLink.Reich'),
        ),
        migrations.AddField(
            model_name='char',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseLink.User'),
        ),
    ]
