# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruestgueter',
            name='directiom',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ruestgueter',
            name='firstX',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruestgueter',
            name='firstY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruestgueter',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ruestgueter',
            name='secondX',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruestgueter',
            name='secondY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruestgueter',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruestgueter',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
