# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0003_auto_20161008_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruestgueter',
            name='direction',
            field=models.CharField(blank=True, choices=[('nw', 'north-west'), ('ne', 'north-east'), ('e', 'east'), ('se', 'south-east'), ('sw', 'south-west'), ('w', 'west')], max_length=2, null=True),
        ),
    ]
