# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0004_auto_20161008_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reichsgebiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('reich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseLink.Reich')),
            ],
        ),
        migrations.RemoveField(
            model_name='karte',
            name='reich',
        ),
        migrations.DeleteModel(
            name='Karte',
        ),
    ]
