# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0005_auto_20161014_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[(b'MV', b'move'), (b'BT', b'battle'), (b'BD', b'build'), (b'RC', b'recruitment'), (b'CM', b'comment'), (b'OT', b'other')], max_length=2, null=True)),
                ('content', models.CharField(blank=True, max_length=250, null=True)),
                ('processed', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='char',
            name='user',
        ),
        migrations.AddField(
            model_name='char',
            name='firstName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='char',
            name='reich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseLink.Reich'),
        ),
        migrations.AddField(
            model_name='char',
            name='secondName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reichszugehoerigkeit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
