# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0006_auto_20161201_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[(b'MV', b'move'), (b'BT', b'battle'), (b'BD', b'build'), (b'RC', b'recruitment'), (b'TN', b'turn'), (b'CM', b'comment'), (b'OT', b'other')], max_length=2, null=True),
        ),
    ]
