# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0008_auto_20161205_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='content',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='processed',
        ),
    ]
