# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0009_auto_20161205_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='processed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[(b'MV', b'move'), (b'BT', b'battle'), (b'BD', b'build'), (b'RC', b'recruitment'), (b'TN', b'turn'), (b'CM', b'comment'), (b'OT', b'other')], max_length=2, null=True),
        ),
    ]
