# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0011_auto_20161205_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[(b'MV', b'move'), (b'BT', b'battle'), (b'BD', b'build'), (b'RC', b'recruitment'), (b'TN', b'turn'), (b'CM', b'comment'), (b'OT', b'other')], default=b'OT', max_length=2),
        ),
    ]
