# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0016_auto_20170102_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnorder',
            name='realm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseLink.Realm'),
        ),
    ]
