# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0020_auto_20170227_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battleevent',
            name='overrun',
        ),
    ]
