# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-09 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0021_remove_battleevent_overrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SplitEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newArmy', models.IntegerField()),
                ('troops', models.IntegerField()),
                ('leaders', models.IntegerField()),
                ('mounts', models.IntegerField()),
                ('lkp', models.IntegerField()),
                ('skp', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armyFromType', models.IntegerField()),
                ('armyToType', models.IntegerField()),
                ('troops', models.IntegerField()),
                ('leaders', models.IntegerField()),
                ('mounts', models.IntegerField()),
                ('lkp', models.IntegerField()),
                ('skp', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='moveevent',
            old_name='x',
            new_name='from_x',
        ),
        migrations.RenameField(
            model_name='moveevent',
            old_name='y',
            new_name='from_y',
        ),
        migrations.AddField(
            model_name='moveevent',
            name='to_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moveevent',
            name='to_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='troop',
            name='heightPoints',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='troop',
            name='isLoadedIn',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='troop',
            name='movementPoints',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='troop',
            name='status',
            field=models.CharField(choices=[(b'tobe', b'tobe'), (b'active', b'active'), (b'inactive', b'inactive')], default=b'active', max_length=8),
        ),
        migrations.AddField(
            model_name='transferevent',
            name='fromArmy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='databaseLink.Troop'),
        ),
        migrations.AddField(
            model_name='transferevent',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseLink.Realm'),
        ),
        migrations.AddField(
            model_name='transferevent',
            name='toArmy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='databaseLink.Troop'),
        ),
        migrations.AddField(
            model_name='splitevent',
            name='fromArmy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseLink.Troop'),
        ),
        migrations.AddField(
            model_name='splitevent',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseLink.Realm'),
        ),
        migrations.AddField(
            model_name='mergeevent',
            name='fromArmy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='databaseLink.Troop'),
        ),
        migrations.AddField(
            model_name='mergeevent',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseLink.Realm'),
        ),
        migrations.AddField(
            model_name='mergeevent',
            name='toArmy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='databaseLink.Troop'),
        ),
    ]
