# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0021_remove_battleevent_overrun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moveevent',
            old_name='x',
            new_name='to_x',
        ),
        migrations.RenameField(
            model_name='moveevent',
            old_name='y',
            new_name='to_y',
        ),
        migrations.AddField(
            model_name='moveevent',
            name='from_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moveevent',
            name='from_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
