# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-09 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0022_auto_20170421_1148'),
        ('databaseLink', '0022_auto_20171009_0948'),
    ]

    operations = [
    ]
