# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-23 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0023_merge_20171009_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergeevent',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mergeevent',
            name='y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='splitevent',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='splitevent',
            name='y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transferevent',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transferevent',
            name='y',
            field=models.IntegerField(null=True),
        ),
    ]
