# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-04 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0023_auto_20170922_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='troop',
            name='heightPoints',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='troop',
            name='movementPoints',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
