# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-13 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseLink', '0024_auto_20171023_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newArmy', models.IntegerField()),
                ('troops', models.IntegerField()),
                ('leaders', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
                ('fromArmy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseLink.Troop')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseLink.Realm')),
            ],
        ),
    ]
